name: CD Pipeline

on:
  workflow_run:
    workflows: [ "CI Pipeline" ]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull danishyousuf/cicd-pipeline:latest
    - name : Delete old Docker container
      run: sudo docker rm -f cicd-pipeline-container || true
    - name: Run Docker container
      run: sudo docker run -d -p 8083:8083 --name cicd-pipeline-container danishyousuf/cicd-pipeline
      
